BusinessManagement/views/admin.py
import io
import csv
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback
admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET","POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        print('file name1 --',file.filename, file.filename.lower().endswith('.csv'))
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
         # TODO importcsv-1 check that it's a .csv file, return a proper flash message if it's not
        elif file.filename.lower().endswith('.csv'):
            print('file name --',file.filename)
        else:
            flash('Invalid File ', "warning")
            return redirect(request.url)

        #UCID:vg473; Date: 04/08/23
        if file and secure_filename(file.filename):
            companies = []
            employees = []
            # DON'T EDIT
            company_query = """
            INSERT INTO IS601_MP3_Companies (name, address, city, country, state, zip, website)
                        VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s)
                        ON DUPLICATE KEY UPDATE 
                        address=values(address),
                        city=values(city),
                        country=values(country),
                        state=values(state),
                        zip=values(zip),
                        website=values(website)
            """
            # DON'T EDIT
            employee_query = """
             INSERT INTO IS601_MP3_Employees (first_name, last_name, email, company_id)
                        VALUES (%(first_name)s, %(last_name)s, %(email)s, (SELECT id FROM IS601_MP3_Companies WHERE name = %(company_name)s LIMIT 1))
                        ON DUPLICATE KEY UPDATE first_name=%(first_name)s, 
                        last_name = %(last_name)s, email = %(email)s, 
                        company_id = (SELECT id FROM IS601_MP3_Companies WHERE name=%(company_name)s LIMIT 1)
            """
            # Note: this reads the file as a stream instead of requiring us to save it
            stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
            # TODO importcsv-2 read the csv file stream as a dict
          
            
            for row in csv.DictReader(stream, delimiter=','):
                print(row) #example
                # TODO importcsv-3 extract company data and append to company list 
                # as a dict only with company data if all is present
                if row["company_name"] and row["address"] and row["city"] and row["state"] and row["zip"] and row["web"] and row["country"]:
                   companies.append({"name" : row["company_name"],  "address" :  row["address"], "city" : row["city"], "state" : row["state"], "country" : row["country"],
                    "zip": row["zip"], "website" : row["web"]})
                if row["first_name"] and row["last_name"] and row["email"] and row["company_name"]:
                    employees.append({"first_name" : row["first_name"],  "last_name" :  row["last_name"], "email" : row["email"], "company_name" : row["company_name"]})
                
                # TODO importcsv-4 extract employee data and append to employee list 
                # as a dict only with employee data if all is present
            #UCID:vg473; Date: 04/08/23  
               
            if len(companies) > 0:
                print(f"Inserting or updating {len(companies)} companies")
                try:
                    result = DB.insertMany(company_query, companies)
                    # TODO importcsv-5 display flash message about number of companies inserted
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
            else:
                # TODO importcsv-6 display flash message (info) that no companies were loaded
                pass
            if len(employees) > 0:
                print(f"Inserting or updating {len(employees)} employees")
                try:
                    result = DB.insertMany(employee_query, employees)
                    # TODO importcsv-7 display flash message about number of employees loaded
                    flash(f"Inserted {len(employees)} employees records successfully!", "success")
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error loading in the csv data", "danger")
                    #UCID:vg473; Date: 04/08/23
            else:
                 # TODO importcsv-8 display flash message (info) that no employees were loaded
                  flash("No employees records were loaded", "danger")
            return render_template("upload.html")
            try:
                result = DB.selectOne("SHOW SESSION STATUS LIKE 'questions'")
                print(f"Result {result}")
            except Exception as e:
                    traceback.print_exc()
                    flash("There was an error counting session queries", "danger")
    return render_template("upload.html")
    #UCID:vg473; Date: 04/08/23

BusinessManagement/views/company.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from sql.db import DB
company = Blueprint('company', __name__, url_prefix='/company')

@company.route("/search", methods=["GET"])
def search():
    rows = []
    # DO NOT DELETE PROVIDED COMMENTS
    # TODO search-1 retrieve id, name, address, city, country, state, zip, website, employee count as employees for the company
    # don't do SELECT *

    query = """SELECT c.id, c.name, c.address, c.city, c.country, c.state, c.zip, c.website, COUNT(e.id) AS employees FROM IS601_MP3_Companies c 
    LEFT JOIN IS601_MP3_Employees e ON e.company_id = c.id WHERE 1=1 """
    #UCID:vg473;Date:04/08/23
    args = []  # <--- add values to replace %s/%(named)s placeholders
    allowed_columns = ["name", "city", "country", "state"]
    allowed_list = [(v, v) for v in allowed_columns]
    # TODO search-2 get name, country, state, column, order, limit request args
    name = request.args.get('name')
    country = request.args.get('country')
    state = request.args.get('state')
    limit = 10
    column = request.args.get('column')
    order = request.args.get('order')
    limit = request.args.get('limit')
    #UCID:vg473;Date:04/08/23
    # TODO search-3 append a LIKE filter for name if provided
    if name:
        query += " AND c.name like %s"
        args.append(f"%{name}%")
    # TODO search-4 append an equality filter for country if provided
    if country:
        query += " AND c.country like %s"
        args.append(f"%{country}%")
    # TODO search-5 append an equality filter for state if provided
    if state:
        query += " AND c.state like %s"
        args.append(f"%{state}%")
    #UCID:vg473;Date:04/08/23
    query += " GROUP BY c.id"
    # TODO search-6 append sorting if column and order are provided and within the allows columsn and allowed order asc,desc
    if column and order:
        if column in allowed_columns and order in ["asc", "desc"]:
            query += f" ORDER BY {column} {order}"
     #UCID:vg473;Date:04/08/23
    # TODO search-7 append limit (default 10) or limit greater than 1 and less than or equal to 100
    # TODO search-8 provide a proper error message if limit isn't a number or if it's out of bounds
    if limit and int(limit) > 0 and int(limit) <= 100:
        query += " LIMIT %s"
        args.append(int(limit))
    elif limit and (int(limit) <= 0 or int(limit) > 100):
        flash("Enter the limit between 1 and 100", 'warning')
         #UCID:vg473;Date:04/08/23

    print("query", query)
    print("args", args)
    try:
        result = DB.selectAll(query, *args)
        # print(f"result {result.rows}")
        if result.status:
            rows = result.rows
            print(f"rows {rows}")
    except Exception as e:
        # TODO search-9 make message user friendly
        flash(str(e), "danger")
    # hint: use allowed_columns in template to generate sort dropdown
    # hint2: convert allowed_columns into a list of tuples representing (value, label)
    # do this prior to passing to render_template, but not before otherwise it can break validation

    return render_template("list_companies.html", rows=rows, allowed_columns=allowed_list)
    #UCID:vg473;Date:04/08/23


@company.route("/add", methods=["GET", "POST"])
def add():
    if request.method == "POST":
        # TODO add-1 retrieve form data for name, address, city, state, country, zip, website
        # TODO add-2 name is required (flash proper error message)
        # TODO add-3 address is required (flash proper error message)
        # TODO add-4 city is required (flash proper error message)
        # TODO add-5 state is required (flash proper error message)
        # TODO add-5a state should be a valid state mentioned in pycountry for the selected state
        # hint see geography.py and pycountry documentation
        # TODO add-6 country is required (flash proper error message)
        # TODO add-6a country should be a valid country mentioned in pycountry
        # hint see geography.py and pycountry documentation
        # TODO add-7 website is not required
        # TODO add-8 zipcode is required (flash proper error message)
        # note: call zip variable zipcode as zip is a built in function it could lead to issues

        has_error = False  # use this to control whether or not an insert occurs

        name = str(request.form['name'])
        if not name:
            has_error = True
            flash("Company name is required", "danger")
        address = str(request.form['address'])
        if not address:
            has_error = True
            flash("Address is required", "danger")
        city = str(request.form['city'])
        if not city:
            has_error = True
            flash("city is required", "danger")
        country = str(request.form['country'])
        state = str(request.form['state'])
        zip = str(request.form['zip'])
        if not name:
            has_error = True
            flash("Zipcode is required", "danger")
        website = str(request.form['website'])
        #UCID:vg473;Date:04/08/23

        if not has_error:
            try:
                result = DB.insertOne("""
                INSERT INTO IS601_MP3_Companies
                (name, address, city, country, state, zip, website) VALUES(%s, %s, %s, %s, %s, %s, %s)
                """, name, address, city, country, state, zip, website)  # <-- TODO add-8 add query and add arguments
                #UCID:vg473;Date:04/08/23
                if result.status:
                    flash("Added Company", "success")
            except Exception as e:
                # TODO add-9 make message user friendly
                flash(str(e), "danger")

    return render_template("add_company.html")


@company.route("/edit", methods=["GET", "POST"])
def edit():
    # TODO edit-1 request args id is required (flash proper error message)
    id = request.args.get('id') or False
    if not id:  # TODO update this for TODO edit-1
        flash("Company ID is missing", "danger")
    else:
        if request.method == "POST":
            # use this as needed, can convert to tuple if necessary
            data = {"id": id}
            # TODO edit-1 retrieve form data for name, address, city, state, country, zip, website
            # TODO edit-2 name is required (flash proper error message)
            # TODO edit-3 address is required (flash proper error message)
            # TODO edit-4 city is required (flash proper error message)
            # TODO edit-5 state is required (flash proper error message)
            # TODO edit-5a state should be a valid state mentioned in pycountry for the selected state
            # hint see geography.py and pycountry documentation
            # TODO edit-6 country is required (flash proper error message)
            # TODO edit-6a country should be a valid country mentioned in pycountry
            # hint see geography.py and pycountry documentation
            # TODO edit-7 website is not required
            # TODO edit-8 zipcode is required (flash proper error message)

            # note: call zip variable zipcode as zip is a built in function it could lead to issues
            # populate data dict with mappings
            has_error = False  # use this to control whether or not an insert occurs


            name = str(request.form.get('name'))
            if not name:
                has_error = True
                flash("Company name is required", "danger")
            address = str(request.form.get('address'))
            if not address:
                has_error = True
                flash("Address is required", "danger")
            city = str(request.form.get('city'))
            if not city:
                has_error = True
                flash("city is required", "danger")
            country = str(request.form.get('country'))
            state = str(request.form.get('state'))
            zip = str(request.form.get('zip'))
            if not zip:
                has_error = True
                flash("Zipcode is required", "danger")
            website = str(request.form.get('website') or '')
            #UCID:vg473;Date:04/08/23

            if not has_error:
                try:
                    # TODO edit-9 fill in proper update query
                    # name, address, city, state, country, zip, website
                    result = DB.update("""
                    UPDATE IS601_MP3_Companies
                    SET
                        name = %s,
                        address = %s,
                        city = %s,
                        country = %s,
                        state = %s,
                        zip = %s,
                        website = %s
                    WHERE id = %s
                    """, name, address, city, country, state, zip, website, id)
                                #UCID:vg473;Date:04/08/23

                    if result.status:
                        print("updated record")
                        flash("Updated record", "success")
                except Exception as e:
                    # TODO edit-10 make this user-friendly
                    print(f"{e}")
                    flash(str(e), "danger")
                    #UCID:vg473;Date:04/08/23
    row = {}
    try:
        # TODO edit-11 fetch the updated data
        result = DB.selectOne(
            "SELECT name, address, city, country, state, zip, website FROM IS601_MP3_Companies WHERE id = %s", id)
        if result.status:
            row = result.row
    #UCID:vg473;Date:04/08/23
    except Exception as e:
        # TODO edit-12 make this user-friendly
        flash(str(e), "danger")
    # TODO edit-13 pass the company data to the render template
    return render_template("edit_company.html", company=row)
#UCID:vg473;Date:04/08/23

@company.route("/delete", methods=["GET"])
def delete():
    # TODO delete-1 delete company by id (unallocate any employees see delete-5)

BusinessManagement/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    country_code = request.args.get("country_code", default="", type=str)
    states = []
    if country_code.strip():
        states = pycountry.subdivisions.get(country_code=country_code.strip())
    print(f"Found [{len(states)}] states for country_code [{country_code}]")
    if not states:
        states = []
    states = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        states))
    return json.dumps(states)

BusinessManagement/views/index.py
from flask import Blueprint, render_template
home = Blueprint('home', __name__, url_prefix='/')

# TODO DO NOT EDIT
@home.route('/')
def index():
    return render_template("index.html")

BusinessManagement/templates/add_company.html
{% extends "layout.html" %}
{% block title %}Add Company{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}

<div class="container-fluid">
    <div class="h1">Add Company</div>
    <div>

        <form method="POST">
            {#
            using regular html generate fields (labels and input) with proper types for
            name (required)
            address (required)
            city (required) (can be a text field, doesn't need to be a valid city)
            state/country (required) (given)
            zip (required)
            website (optional)
            if a validation error occurs, the inserted form data should persist
            #}

            <div class="form-group mb-3">
                <label for="name" class="form-label">name</label>
                <input id="name" class="form-control" name="name" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->


            <div class="form-group mb-3">
                <label for="address" class="form-label">address</label>
                <input id="address" class="form-control" name="address" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            <div class="form-group mb-3">
                <label for="city" class="form-label">city</label>
                <input id="city" class="form-control" name="city" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            <div class="form-group mb-3">
                <label for="website" class="form-label">website</label>
                <input id="website" class="form-control" name="website" type="url" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->
            
            <div class="form-group mb-3">
                <label for="zip" class="form-label">zip</label>
                <input id="zip" class="form-control" name="zip" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            {# use this for country/state selection #}
            {{country_state_selector()}}
            <input type="submit" class="btn btn-primary" value="Save Company" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/add_employee.html
{% extends "layout.html" %}
{% block title %}Add Employee{% endblock %}
{% block content %}
{% from "company_dropdown.html" import company_dropdown %}
<div class="container-fluid">
    <div class="h1">Add Employee</div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for
            first_name (required)
            last_name (required)
            email (required)
            if a validation error occurs, the inserted form data should persist
            #}


            <div class="form-group mb-3">
                <label for="first_name" class="form-label">first_name</label>
                <input id="first_name" class="form-control" name="first_name" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            <div class="form-group mb-3">
                <label for="last_name" class="form-label">last_name</label>
                <input id="last_name" class="form-control" name="last_name" type="text" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            <div class="form-group mb-3">
                <label for="email" class="form-label">email</label>
                <input id="email" class="form-control" name="email" type="email" value="">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->
            {# use the below for company selection #}
            {{ company_dropdown() }}
            <input type="submit" class="btn btn-primary" value="Save Employee" />
        </form>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/company_dropdown.html
{% macro company_dropdown(val="") %}
{% set comps = get_companies() %}
{# TODO DO NOT EDIT #}
<select class="form-select mb-3" name="company" value="{{val or ''}}">
    <option value="">No Company</option>
    {% for c in comps %}
    {# example of using external data setting and casting #}
    <option {{'selected' if val|string==c['id']|string}} value="{{c['id']}}">{{c['name']}}</option>
    {% endfor %}
</select>
{% endmacro %}

BusinessManagement/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% macro country_state_selector(country="", state="", layout="vertical") %}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}" required onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}" required>
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    }
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>
{% endmacro %}

BusinessManagement/templates/list_companies.html
{% extends "layout.html" %}
{% block title %}Company Directory{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">Company Directory</div>
    {# TODO
    build a horizontal filter/sort form with
    name (show as company name but name field should be name)
    country/state (provided)
    sort/order (using allowed_columns and provided partial template)
    limit (default 10)
    ensure all fields prefill with request arg data if provided
    #}
    <form method="GET">
        <div class="row">
            <div class="col">
                <input id="name" class="form-control" placeholder="name" name="name" type="text"
                    value="{{ allowed_columns[0].value }}">
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->

            {{country_state_selector(layout="horizontal")}}
            {{sort_filter(cols=allowed_columns)}}
            <div class="col">
                <input id="limit" type="number" class="form-control" value="10" name="limit" />
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->
            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <!-- UCID: vg473; Date: 04/08/23 -->
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            {% if rows and rows|length > 0 %}
            <thead>
                <tr class="text-capitalize">
                    {# generate th tags for each column to display #}
                    {# IMPORTANT use table column names as the headings, replace _ with space via filter #}
                    <th>id</th>
                    <th>name</th>
                    <th>address</th>
                    <th>city</th>
                    <th>country</th>
                    <th>state</th>
                    <th>zip</th>
                    <th>website</th>
                    <th>employees</th>
                    <th>Actions</th>
                </tr>
                <!-- UCID: vg473; Date: 04/08/23 -->
            </thead>
            <tbody>
                {# generate tr with td tags for each piece of data #}
                {# if the td is for website, display it as a link where the text is "website" and the url is the
                website url #}
                {# in the last column add the following
                a view button that passes the company id to employee search (this will be a company employee
                directory) also pass company_name as an argument
                an edit button that passes the company id to company edit
                a delete button that passes the company id and the request args to the company delete route
                #}
                {% for row in rows %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.address }}</td>
                    <td>{{ row.city }}</td>
                    <td>{{ row.country }}</td>
                    <td>{{ row.state }}</td>
                    <td>{{ row.zip }}</td>
                    <td><a href="{{ row.website }}">website</a></td>
                    <td>{{ row.employees }}</td>
                    <td>
                        <a href="{{url_for('company.edit', id=row.id)}}">Edit</a>
                        <a href="{{url_for('company.delete', id=row.id)}}">Delete</a>
                    </td>
                    <!-- UCID: vg473; Date: 04/08/23 -->
                </tr>
                {% endfor %}

            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="100%">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

BusinessManagement/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO replace my ucid mt85 with your ucid in the below a tag #}
        <a class="navbar-brand" href="{{url_for('home.index')}}">DIAR-vg473</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO fill in the relevant hrefs using url_for() #}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- company dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Company
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('company.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('company.add')}}">Add</a></li>
                    </ul>
                    <!-- UCID: vg473; Date: 04/08/23 -->
                </li>
                <!-- employee dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Employee
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('employee.search')}}">Search</a></li>
                        <li><a class="dropdown-item" href="{{url_for('employee.add')}}">Add</a></li>
                    </ul>
                    <!-- UCID: vg473; Date: 04/08/23 -->
                </li>
                <!-- admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{url_for('admin.importCSV')}}">Import</a></li>
                        <!-- UCID: vg473; Date: 04/08/23 -->
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>